services:
  postgres:
    env_file: ./.env
    image: postgres:15
    container_name: postgres_for_train_up
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: train_up
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
